title: Myndr Help center
description: Antwoord op al je vragen over Myndr, de Myndr switch en het dagelijks gebruik ervan.
theme: just-the-docs

url: "https://kb.myndr.nl/" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: myndr_nl
#github_username:  myndr
logo: "https://permalink.myndr.net/logo_hor-trns.png"
favicon_ico: "https://permalink.myndr.net/favicon.ico"

# Build settings

aux_links:
  English: "//kb.myndr.com/"
  Naar de Myndr website: "//www.myndr.nl/"
